### Build the SDoH KG

In [1]:
import pandas as pd

#### combine results

In [41]:
df1 = pd.read_csv('result/server/resultgpt-4o.csv')
df1.loc[-1] = df1.columns  # Add the column names as the first row
df1.index = df1.index + 1  # Shift the index
df1 = df1.sort_index()  # Sort the index to make the first row at the top
df1.columns = ['Bio', 'Relationship', 'SDoH factor', 'identifier', 'Bio_type', 'source', 'pmid', 'sub_type', 'type', 'probability']

df2 = pd.read_csv('result/server/coo (3).csv')
df2.loc[-1] = df2.columns  # Add the column names as the first row
df2.index = df2.index + 1  # Shift the index
df2 = df2.sort_index()  # Sort the index to make the first row at the top
df2.columns = ['Bio', 'Relationship', 'SDoH factor', 'identifier', 'Bio_type', 'source', 'pmid', 'sub_type', 'type', 'probability']

df3 = pd.read_csv('result/test/resultgpt-4o.csv')
df3.loc[-1] = df3.columns  # Add the column names as the first row
df3.index = df3.index + 1  # Shift the index
df3 = df3.sort_index()  # Sort the index to make the first row at the top
df3.columns = ['Bio', 'Relationship', 'SDoH factor', 'identifier', 'Bio_type', 'source', 'pmid', 'sub_type', 'type', 'probability']

In [53]:
result = pd.concat([df1, df2]).reset_index(drop=True)
result = pd.concat([result, df3]).reset_index(drop=True)
result['sub_type'] = result['sub_type'].astype(float).astype(int)
result['type'] = result['sub_type'].astype(float).astype(int)
result['probability'] = result['probability'].astype(float)
result

,Bio,Relationship,SDoH factor,identifier,Bio_type,source,pmid,sub_type,type,probability
0,patients,responsible,caregivers,9606,Species,ncbi_taxonomy,35484699,4,4,0.500000
1,dementia,associates,race,MESH:D003704,Disease,ncbi_mesh,31601516,2,2,0.500000
2,dementia,affects,families,MESH:D003704,Disease,ncbi_mesh,34962459,4,4,0.428571
3,dementia,affects,family member,MESH:D003704,Disease,ncbi_mesh,34962459,4,4,0.428571
4,dementia,associates,diagnosis,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.500000
...,...,...,...,...,...,...,...,...,...,...
3291,heart disease,associates,poor nutrition,MESH:D006331,Disease,ncbi_mesh,38304166,1,1,0.500000
3292,respiratory diseases,associates,poor nutrition,MESH:D012140,Disease,ncbi_mesh,38304166,1,1,1.000000
3293,dementia,associates,disparities,MESH:D003704,Disease,ncbi_mesh,38384925,2,2,1.000000
3294,Dementia,associates,representation,MESH:D003704,Disease,ncbi_mesh,38460119,1,1,0.500000
3295,Alzheimer's disease,places burden on,families,MESH:D000544,Disease,ncbi_mesh,38560360,4,4,1.000000

In [54]:
# for each row, if 'identifier' 'sub_type' 'type' are the same, keep the row with the highest 'probability'
result = result.sort_values('probability', ascending=False).drop_duplicates(['identifier', 'SDoH factor']).sort_index() 
result

,Bio,Relationship,SDoH factor,identifier,Bio_type,source,pmid,sub_type,type,probability
4,dementia,associates,diagnosis,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
5,dementia,associates,disease-modifying treatments,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
6,dementia,associates,elderly care,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
7,dementia,associates,guidelines,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
8,dementia,associates,protocols,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
...,...,...,...,...,...,...,...,...,...,...
3291,heart disease,associates,poor nutrition,MESH:D006331,Disease,ncbi_mesh,38304166,1,1,0.5
3292,respiratory diseases,associates,poor nutrition,MESH:D012140,Disease,ncbi_mesh,38304166,1,1,1.0
3293,dementia,associates,disparities,MESH:D003704,Disease,ncbi_mesh,38384925,2,2,1.0
3294,Dementia,associates,representation,MESH:D003704,Disease,ncbi_mesh,38460119,1,1,0.5
3295,Alzheimer's disease,places burden on,families,MESH:D000544,Disease,ncbi_mesh,38560360,4,4,1.0

In [55]:
result.to_csv('result/resultgpt-4o.csv', index=False)

In [65]:
SDoH_df = pd.read_csv('result/resultgpt-4o.csv')
SDoH_df

,Bio,Relationship,SDoH factor,identifier,Bio_type,source,pmid,sub_type,type,probability
0,dementia,associates,diagnosis,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
1,dementia,associates,disease-modifying treatments,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
2,dementia,associates,elderly care,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
3,dementia,associates,guidelines,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
4,dementia,associates,protocols,MESH:D003704,Disease,ncbi_mesh,35301255,1,1,0.5
...,...,...,...,...,...,...,...,...,...,...
2704,heart disease,associates,poor nutrition,MESH:D006331,Disease,ncbi_mesh,38304166,1,1,0.5
2705,respiratory diseases,associates,poor nutrition,MESH:D012140,Disease,ncbi_mesh,38304166,1,1,1.0
2706,dementia,associates,disparities,MESH:D003704,Disease,ncbi_mesh,38384925,2,2,1.0
2707,Dementia,associates,representation,MESH:D003704,Disease,ncbi_mesh,38460119,1,1,0.5
2708,Alzheimer's disease,places burden on,families,MESH:D000544,Disease,ncbi_mesh,38560360,4,4,1.0

#### map type and sub_type (int -> str)

In [57]:
type = ['healthcare access and quality', 'education access and quality', 'social and community context', 'economic stability', 'neighborhood and built environment']
sub_type = [['Access to Health Services', 'Access to Primary Care', 'Health Literacy'],
                  ['Early Childhood Development and Education', 'Enrollment in Higher Education', 'High School Graduation', 'Language and Literacy'],
                  ['Civic Participation', 'Discrimination', 'Incarceration', 'Social Cohesion'],
                  ['Employment', 'Food Insecurity', 'Housing Instability', 'Poverty'],
                  ['Access to Foods That Support Healthy Dietary Patterns' ,'Crime and Violence' ,'Environmental Conditions' ,'Quality of Housing']]

In [77]:
# Create a list to store the rows
rows = []

# Loop through types and their corresponding sub_types
for type_value, sub_type_list in zip(type, sub_type):
    for sub_type_value in sub_type_list:
        rows.append({'relation': 'subordinate', 'x_name': sub_type_value, 'x_id': 'NaN', 'x_type':'SDoH subtype', 'x_source':'healthypeople',
                     'y_name': type_value, 'y_id': 'NaN', 'y_type':'SDoH type', 'y_source':'healthypeople', 'pmid': 'NaN', 'probability': 1.0})
# Create the DataFrame
typedf = pd.DataFrame(rows)
typedf

,relation,x_name,x_id,x_type,x_source,y_name,y_id,y_type,y_source,pmid,probability
0,subordinate,Access to Health Services,NaN,SDoH subtype,healthypeople,healthcare access and quality,NaN,SDoH type,healthypeople,NaN,1.0
1,subordinate,Access to Primary Care,NaN,SDoH subtype,healthypeople,healthcare access and quality,NaN,SDoH type,healthypeople,NaN,1.0
2,subordinate,Health Literacy,NaN,SDoH subtype,healthypeople,healthcare access and quality,NaN,SDoH type,healthypeople,NaN,1.0
3,subordinate,Early Childhood Development and Education,NaN,SDoH subtype,healthypeople,education access and quality,NaN,SDoH type,healthypeople,NaN,1.0
4,subordinate,Enrollment in Higher Education,NaN,SDoH subtype,healthypeople,education access and quality,NaN,SDoH type,healthypeople,NaN,1.0
5,subordinate,High School Graduation,NaN,SDoH subtype,healthypeople,education access and quality,NaN,SDoH type,healthypeople,NaN,1.0
6,subordinate,Language and Literacy,NaN,SDoH subtype,healthypeople,education access and quality,NaN,SDoH type,healthypeople,NaN,1.0
7,subordinate,Civic Participation,NaN,SDoH subtype,healthypeople,social and community context,NaN,SDoH type,healthypeople,NaN,1.0
8,subordinate,Discrimination,NaN,SDoH subtype,healthypeople,social and community context,NaN,SDoH type,healthypeople,NaN,1.0
9,subordinate,Incarceration,NaN,SDoH subtype,healthypeople,social and community context,NaN,SDoH type,healthypeople,NaN,1.0
10,subordinate,Social Cohesion,NaN,SDoH subtype,healthypeople,social and community context,NaN,SDoH type,healthypeople,NaN,1.0
11,subordinate,Employment,NaN,SDoH subtype,healthypeople,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
12,subordinate,Food Insecurity,NaN,SDoH subtype,healthypeople,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
13,subordinate,Housing Instability,NaN,SDoH subtype,healthypeople,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
14,subordinate,Poverty,NaN,SDoH subtype,healthypeople,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
15,subordinate,Access to Foods That Support Healthy Dietary P...,NaN,SDoH subtype,healthypeople,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
16,subordinate,Crime and Violence,NaN,SDoH subtype,healthypeople,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
17,subordinate,Environmental Conditions,NaN,SDoH subtype,healthypeople,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
18,subordinate,Quality of Housing,NaN,SDoH subtype,healthypeople,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0

In [66]:
# for each row in SDoH_df, change the 'type' and 'sub_type' to the corresponding values
for i in range(len(SDoH_df)):
    SDoH_df.loc[i, 'sub_type'] = sub_type[int(SDoH_df.loc[i, 'type'])-1][int(SDoH_df.loc[i, 'sub_type'])-1] 
    SDoH_df.loc[i, 'type'] = type[int(SDoH_df.loc[i, 'type'])-1]

SDoH_df

,Bio,Relationship,SDoH factor,identifier,Bio_type,source,pmid,sub_type,type,probability
0,dementia,associates,diagnosis,MESH:D003704,Disease,ncbi_mesh,35301255,Access to Health Services,healthcare access and quality,0.5
1,dementia,associates,disease-modifying treatments,MESH:D003704,Disease,ncbi_mesh,35301255,Access to Health Services,healthcare access and quality,0.5
2,dementia,associates,elderly care,MESH:D003704,Disease,ncbi_mesh,35301255,Access to Health Services,healthcare access and quality,0.5
3,dementia,associates,guidelines,MESH:D003704,Disease,ncbi_mesh,35301255,Access to Health Services,healthcare access and quality,0.5
4,dementia,associates,protocols,MESH:D003704,Disease,ncbi_mesh,35301255,Access to Health Services,healthcare access and quality,0.5
...,...,...,...,...,...,...,...,...,...,...
2704,heart disease,associates,poor nutrition,MESH:D006331,Disease,ncbi_mesh,38304166,Access to Health Services,healthcare access and quality,0.5
2705,respiratory diseases,associates,poor nutrition,MESH:D012140,Disease,ncbi_mesh,38304166,Access to Health Services,healthcare access and quality,1.0
2706,dementia,associates,disparities,MESH:D003704,Disease,ncbi_mesh,38384925,Enrollment in Higher Education,education access and quality,1.0
2707,Dementia,associates,representation,MESH:D003704,Disease,ncbi_mesh,38460119,Access to Health Services,healthcare access and quality,0.5
2708,Alzheimer's disease,places burden on,families,MESH:D000544,Disease,ncbi_mesh,38560360,Poverty,economic stability,1.0

break [bio-sdoh-sub_type-type] to 
1. bio-sdoh (SDoHKG1)
2. sdoh-sub_type (SDoHKG2)
3. sub_type-type (typedf)

In [69]:
SDoHKG1 = SDoH_df[['Relationship', 'Bio', 'identifier', 'Bio_type', 'source', 'SDoH factor', 'pmid', 'probability' ]].copy()
#rename the columns
SDoHKG1.columns = ['relation', 'x_name', 'x_id', 'x_type', 'x_source', 'y_name', 'pmid', 'probability']
# SDoHKG1.loc[:, 'y_id'] = 'NaN'
# SDoHKG1.loc[:, 'y_type'] = 'SDoH factor'
# SDoHKG1.loc[:, 'y_source'] = 'NaN'
SDoHKG1['y_id'] = 'NaN'
SDoHKG1['y_type'] = 'SDoH factor'
SDoHKG1['y_source'] = 'healthypeople'
# move the column 'y_id' to the left of 'probability'
SDoHKG1 = SDoHKG1[['relation', 'x_name', 'x_id', 'x_type', 'x_source', 'y_name', 'y_id', 'y_type', 'y_source', 'pmid', 'probability' ]]
SDoHKG1 = SDoHKG1.drop_duplicates(subset=['x_id', 'y_name'], keep='first')
SDoHKG1

,relation,x_name,x_id,x_type,x_source,y_name,y_id,y_type,y_source,pmid,probability
0,associates,dementia,MESH:D003704,Disease,ncbi_mesh,diagnosis,NaN,SDoH factor,healthypeople,35301255,0.5
1,associates,dementia,MESH:D003704,Disease,ncbi_mesh,disease-modifying treatments,NaN,SDoH factor,healthypeople,35301255,0.5
2,associates,dementia,MESH:D003704,Disease,ncbi_mesh,elderly care,NaN,SDoH factor,healthypeople,35301255,0.5
3,associates,dementia,MESH:D003704,Disease,ncbi_mesh,guidelines,NaN,SDoH factor,healthypeople,35301255,0.5
4,associates,dementia,MESH:D003704,Disease,ncbi_mesh,protocols,NaN,SDoH factor,healthypeople,35301255,0.5
...,...,...,...,...,...,...,...,...,...,...,...
2704,associates,heart disease,MESH:D006331,Disease,ncbi_mesh,poor nutrition,NaN,SDoH factor,healthypeople,38304166,0.5
2705,associates,respiratory diseases,MESH:D012140,Disease,ncbi_mesh,poor nutrition,NaN,SDoH factor,healthypeople,38304166,1.0
2706,associates,dementia,MESH:D003704,Disease,ncbi_mesh,disparities,NaN,SDoH factor,healthypeople,38384925,1.0
2707,associates,Dementia,MESH:D003704,Disease,ncbi_mesh,representation,NaN,SDoH factor,healthypeople,38460119,0.5
2708,places burden on,Alzheimer's disease,MESH:D000544,Disease,ncbi_mesh,families,NaN,SDoH factor,healthypeople,38560360,1.0

In [75]:
SDoHKG2 = SDoH_df[['Relationship', 'SDoH factor', 'sub_type', 'pmid', 'probability']].copy()
#change relationship values to to subordinate, probability to 1
SDoHKG2.loc[:, 'Relationship'] = 'subordinate'
SDoHKG2.loc[:, 'probability'] = 1.0
SDoHKG2.loc[:, 'x_id'] = 'NaN'
SDoHKG2.loc[:, 'x_type'] = 'SDoH factor'
SDoHKG2.loc[:, 'x_source'] = 'healthypeople'
SDoHKG2.loc[:, 'y_id'] = 'NaN'
SDoHKG2.loc[:, 'y_type'] = 'SDoH subtype'
SDoHKG2.loc[:, 'y_source'] = 'healthypeople'
#rename the columns
SDoHKG2.columns = ['relation', 'x_name', 'y_name', 'pmid', 'probability', 'x_id', 'x_type', 'x_source',  'y_id', 'y_type', 'y_source']
SDoHKG2 = SDoHKG2[['relation', 'x_name', 'x_id', 'x_type', 'x_source', 'y_name', 'y_id', 'y_type', 'y_source', 'pmid', 'probability' ]]
SDoHKG2['x_name'] = SDoHKG2['x_name'].str.lower()
SDoHKG2 = SDoHKG2.drop_duplicates(subset=['x_name', 'y_name'], keep='first')
SDoHKG2

,relation,x_name,x_id,x_type,x_source,y_name,y_id,y_type,y_source,pmid,probability
0,subordinate,diagnosis,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,35301255,1.0
1,subordinate,disease-modifying treatments,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,35301255,1.0
2,subordinate,elderly care,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,35301255,1.0
3,subordinate,guidelines,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,35301255,1.0
4,subordinate,protocols,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,35301255,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2699,subordinate,non-hispanic black,NaN,SDoH factor,healthypeople,Enrollment in Higher Education,NaN,SDoH subtype,healthypeople,37984835,1.0
2701,subordinate,utility hardship,NaN,SDoH factor,healthypeople,Poverty,NaN,SDoH subtype,healthypeople,38087286,1.0
2702,subordinate,income segregation,NaN,SDoH factor,healthypeople,Poverty,NaN,SDoH subtype,healthypeople,38217979,1.0
2703,subordinate,poor nutrition,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,38304166,1.0
2707,subordinate,representation,NaN,SDoH factor,healthypeople,Access to Health Services,NaN,SDoH subtype,healthypeople,38460119,1.0

concat the 3 subgraphs, set the index to -1

In [78]:
#merge SDoHKG and SDoHKG1
SDoHKG = pd.concat([SDoHKG1, SDoHKG2], axis=0).reset_index(drop=True)
#merge SDoHKG and typedf
SDoHKG = pd.concat([SDoHKG, typedf], axis=0).reset_index(drop=True)
SDoHKG['x_index'] = -1
SDoHKG['y_index'] = -1
# Step 2: Reorder the columns to place 'index' as the second column
cols = SDoHKG.columns.tolist()
cols.insert(1, cols.pop(cols.index('x_index')))
cols.insert(6, cols.pop(cols.index('y_index')))
# drop duplicate
#SDoHKG.drop_duplicates(inplace=True)

# reset index
SDoHKG.reset_index(drop=True, inplace=True)
SDoHKG = SDoHKG[cols]
SDoHKG

,relation,x_index,x_name,x_id,x_type,x_source,y_index,y_name,y_id,y_type,y_source,pmid,probability
0,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,diagnosis,NaN,SDoH factor,healthypeople,35301255,0.5
1,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,disease-modifying treatments,NaN,SDoH factor,healthypeople,35301255,0.5
2,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,elderly care,NaN,SDoH factor,healthypeople,35301255,0.5
3,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,guidelines,NaN,SDoH factor,healthypeople,35301255,0.5
4,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,protocols,NaN,SDoH factor,healthypeople,35301255,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4053,subordinate,-1,Poverty,NaN,SDoH subtype,healthypeople,-1,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
4054,subordinate,-1,Access to Foods That Support Healthy Dietary P...,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4055,subordinate,-1,Crime and Violence,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4056,subordinate,-1,Environmental Conditions,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4057,subordinate,-1,Quality of Housing,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0

In [79]:
SDoHKG.to_csv('data\SDoHKG.csv', index=False)

### Entitiy mapping

get the entities of primeKG: pkg

In [88]:
primeKG = pd.read_csv('data\kg.csv', low_memory=False)
primeKG

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
0,protein_protein,ppi,0,9796,gene/protein,PHYHIP,NCBI,8889,56992,gene/protein,KIF15,NCBI
1,protein_protein,ppi,1,7918,gene/protein,GPANK1,NCBI,2798,9240,gene/protein,PNMA1,NCBI
2,protein_protein,ppi,2,8233,gene/protein,ZRSR2,NCBI,5646,23548,gene/protein,TTC33,NCBI
3,protein_protein,ppi,3,4899,gene/protein,NRF1,NCBI,11592,11253,gene/protein,MAN1B1,NCBI
4,protein_protein,ppi,4,5297,gene/protein,PI4KA,NCBI,2122,8601,gene/protein,RGS20,NCBI
...,...,...,...,...,...,...,...,...,...,...,...,...
8100493,anatomy_protein_absent,expression absent,66747,4720,anatomy,cerebellar vermis,UBERON,5259,140,gene/protein,ADORA3,NCBI
8100494,anatomy_protein_absent,expression absent,63824,1377,anatomy,quadriceps femoris,UBERON,58254,105378952,gene/protein,KLF18,NCBI
8100495,anatomy_protein_absent,expression absent,63826,1379,anatomy,vastus lateralis,UBERON,58254,105378952,gene/protein,KLF18,NCBI
8100496,anatomy_protein_absent,expression absent,64523,2084,anatomy,heart left ventricle,UBERON,58254,105378952,gene/protein,KLF18,NCBI
8100497,anatomy_protein_absent,expression absent,67302,5384,anatomy,nasal cavity epithelium,UBERON,58254,105378952,gene/protein,KLF18,NCBI

In [89]:
pkg1 = primeKG[['x_index', 'x_name', 'x_id', 'x_type', 'x_source']]
pkg2 = primeKG[['y_index', 'y_name', 'y_id', 'y_type', 'y_source']]
pkg2.columns = ['x_index', 'x_name', 'x_id', 'x_type', 'x_source']
# concat pkg1 and pkg2
pkg = pd.concat([pkg1, pkg2], axis=0)
pkg = pkg.drop_duplicates()
pkg.reset_index(drop=True, inplace=True)
pkg

,x_index,x_name,x_id,x_type,x_source
0,0,PHYHIP,9796,gene/protein,NCBI
1,1,GPANK1,7918,gene/protein,NCBI
2,2,ZRSR2,8233,gene/protein,NCBI
3,3,NRF1,4899,gene/protein,NCBI
4,4,PI4KA,5297,gene/protein,NCBI
...,...,...,...,...,...
129370,129370,Ion transport by P-type ATPases,R-HSA-936837,pathway,REACTOME
129371,129371,Inhibition of voltage gated Ca2+ channels via...,R-HSA-997272,pathway,REACTOME
129372,129372,anatomical entity,1062,anatomy,UBERON
129373,129373,multi-cellular organism,468,anatomy,UBERON
129374,129374,female gonad,992,anatomy,UBERON

In [108]:
df3 = pkg[['x_type','x_source']]
df3 = df3.drop_duplicates()
df3.reset_index(drop=True, inplace=True)
df3

                x_type       x_source
0         gene/protein           NCBI
1                 drug       DrugBank
2     effect/phenotype            HPO
3              disease  MONDO_grouped
4              disease          MONDO
5   biological_process             GO
6   molecular_function             GO
7   cellular_component             GO
8             exposure            CTD
9              pathway       REACTOME
10             anatomy         UBERON

In [90]:
pkg.to_csv('data/pkg.csv', index=False)

In [5]:
SDoHKG = pd.read_csv('data/SDoHKG.csv', low_memory=False)

In [6]:
SDoHKG

,relation,x_index,x_name,x_id,x_type,x_source,y_index,y_name,y_id,y_type,y_source,pmid,probability
0,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,diagnosis,NaN,SDoH factor,healthypeople,35301255.0,0.5
1,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,disease-modifying treatments,NaN,SDoH factor,healthypeople,35301255.0,0.5
2,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,elderly care,NaN,SDoH factor,healthypeople,35301255.0,0.5
3,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,guidelines,NaN,SDoH factor,healthypeople,35301255.0,0.5
4,associates,-1,dementia,MESH:D003704,Disease,ncbi_mesh,-1,protocols,NaN,SDoH factor,healthypeople,35301255.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4053,subordinate,-1,Poverty,NaN,SDoH subtype,healthypeople,-1,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
4054,subordinate,-1,Access to Foods That Support Healthy Dietary P...,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4055,subordinate,-1,Crime and Violence,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4056,subordinate,-1,Environmental Conditions,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4057,subordinate,-1,Quality of Housing,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0

In [82]:
# get a dataframe that contains all the x_type which are not 'SDoH factor' or 'SDoH subtype'
unmatchbio = SDoHKG[~SDoHKG['x_type'].isin(['SDoH factor', 'SDoH subtype'])] 
unmatchbio = unmatchbio[['x_name', 'x_id', 'x_type', 'x_source']]
unmatchbio.columns = ['name', 'id', 'type', 'source']
unmatchbio = unmatchbio.drop_duplicates()
unmatchbio.reset_index(drop=True, inplace=True)
unmatchbio

                        name               id     type         source
0                   dementia     MESH:D003704  Disease      ncbi_mesh
1                   patients             9606  Species  ncbi_taxonomy
2        Alzheimer's disease     MESH:D000544  Disease      ncbi_mesh
3       amyloid accumulation  MESH:C000718787  Disease      ncbi_mesh
4     cerebral vulnerability     MESH:D002547  Disease      ncbi_mesh
..                       ...              ...      ...            ...
721              hepatitis C     MESH:D019698  Disease      ncbi_mesh
722  domestic violence/abuse     MESH:D019966  Disease      ncbi_mesh
723                knee pain     MESH:D046788  Disease      ncbi_mesh
724          food insecurity     MESH:D005517  Disease      ncbi_mesh
725     respiratory diseases     MESH:D012140  Disease      ncbi_mesh

[726 rows x 4 columns]

In [87]:
df4 = unmatchbio[['type','source']]
df4 = df4.drop_duplicates()
df4.reset_index(drop=True, inplace=True)
df4

       type         source
0   Disease      ncbi_mesh
1   Species  ncbi_taxonomy
2  Chemical      ncbi_mesh
3      Gene      ncbi_gene
4   Disease           omim
5   Variant         litvar
6  CellLine           cvcl

In [88]:
unmatchbio.to_csv('data/unmatchbio.csv', index=False)

In [134]:
xrefs = pd.read_csv('data/xrefs.tsv', sep='\t')
meshMONDO = pd.read_csv('data/meshMONDO.csv', low_memory=False)
meshMONDO = meshMONDO[['mapped_curie', 'curie_id']]
meshMONDO.columns = ['cls', 'xref']
meshMONDO = pd.concat([meshMONDO, xrefs], axis=0).reset_index(drop=True)
# upper case the 'xref' column
meshMONDO['xref'] = meshMONDO['xref'].str.upper()
meshMONDO = meshMONDO.drop_duplicates()
meshMONDO

                  cls             xref
0       MONDO:0018874     MESH:D015470
1       MONDO:0008339     MESH:C566738
2       MONDO:0009233     MESH:C537226
3       MONDO:0007051     MESH:C535655
4       MONDO:0011190     MESH:C566582
...               ...              ...
138714  MONDO:0000978       NCIT:C5854
138715  MONDO:0016646    UMLS:C4273829
138716  MONDO:0016646    MEDGEN:895207
138717  MONDO:0016646  ORPHANET:250932
138718  MONDO:0016646       GARD:20686

[130944 rows x 2 columns]

In [135]:
meshMONDO.to_csv('data/MESH-MONDO.csv', index=False)

In [89]:
import pandas as pd
meshMONDO = pd.read_csv('data/MESH-MONDO.csv', low_memory=False)
meshDB = pd.read_csv('data/Mesh2DrugBank_bioportal.csv', low_memory=False)
pkg = pd.read_csv('data/pkg.csv')
unmatchbio = pd.read_csv('data/unmatchbio.csv')

For each row in unmatchbio, find the correspongding row in pkg

gene: direct match

mesh&disease: use MESH-MONDO.cv, mondo/grouped(some mesh id don't have a matched mondo id), https://github.com/natacourby/Disease_ontologies_for_knowledge_graphs

omim&disease:

mesh&chemical: drugbank

In [104]:
import re
updated_rows = []
for index, row in unmatchbio.iterrows():
    if row['source'] == 'ncbi_gene':
        match = pkg[(pkg['x_id'] == row['id']) & (pkg['x_source'] == 'NCBI')]
        if not match.empty:
            # Add the target DataFrame's columns to the row
            for col in match.columns:
                row[col] = match[col].values[0]
        else: 
            row['x_index'] = 'NaN'
            row['x_name'] = row['name']
            row['x_id'] = row['id']
            row['x_type'] = 'gene/protein'
            row['x_source'] = 'NCBI'

    elif row['source'] == 'ncbi_mesh' and row['type'] == 'Disease': # map mesh disease to MONDO
        # Check if the id is in meshMONDO['curie_id']
        match = meshMONDO[meshMONDO['xref'].str.lower() == row['id'].lower()]
        if not match.empty:
            # Get the corresponding meshMONDO['mapped_curie']
            mapped_curie = match['cls'].values[0]
            # Extract the digits from the right until zero
            match_digits = re.search(r'0*(\d+)', mapped_curie.split(':')[-1])
            extracted_digits = match_digits.group(1)
            # MONDO entities that are not in PrimeKG
            row['x_index'] = 'NaN'
            row['x_name'] = row['name']
            row['x_id'] = extracted_digits
            row['x_type'] = 'disease'
            row['x_source'] = 'MONDO'
            # x_source is MONDO
            pkg_match = pkg[(pkg['x_id'].astype(str) == extracted_digits) & (pkg['x_source'] == 'MONDO')]
            if not pkg_match.empty:
                # Add the target DataFrame's columns to the row
                for col in pkg_match.columns:
                    row[col] = pkg_match[col].values[0]
            # x_source is MONDO_grouped
            pkg['x_id_split'] = pkg['x_id'].apply(lambda x: x.split('_'))
            pkg_match1 = pkg[(pkg['x_id_split'].apply(lambda x: extracted_digits in x)) & (pkg['x_source'] == 'MONDO_grouped')]
            if not pkg_match1.empty:
                # Add the target DataFrame's columns to the row
                for col in pkg_match1.columns:
                    row[col] = pkg_match1[col].values[0]
            # Drop the temporary 'x_id_split' column
            pkg.drop(columns=['x_id_split'], inplace=True)
        else:
            row['x_index'] = 'NaN'
            row['x_name'] = row['name']
            row['x_id'] = row['id']
            row['x_type'] = 'disease'
            row['x_source'] = 'ncbi_mesh'
    elif row['source'] == 'omim' and row['type'] == 'Disease': # map omim disease to MONDO
        pass
    elif row['source'] == 'ncbi_mesh' and row['type'] == 'Chemical': # map mesh chemical to drugbank
        id = row['id'].split(':')[1]
        match = meshDB[meshDB['Mesh_ID'] == id]
        if not match.empty:
            mapped_curie = match['drugBank_ID'].values[0]
            # DB entities that are not in PrimeKG
            row['x_index'] = 'NaN'
            row['x_name'] = row['name']
            row['x_id'] = mapped_curie
            row['x_type'] = 'drug'
            row['x_source'] = 'DrugBank'
            pkg_match = pkg[(pkg['x_id'].astype(str) == mapped_curie) & (pkg['x_source'] == 'DrugBank')]
            if not pkg_match.empty:
                # Add the target DataFrame's columns to the row
                for col in pkg_match.columns:
                    row[col] = pkg_match[col].values[0]
        else:
            row['x_index'] = 'NaN'
            row['x_name'] = row['name']
            row['x_id'] = row['id']
            row['x_type'] = 'drug'
            row['x_source'] = 'ncbi_mesh'

    # match for other types that are not in PrimeKG
    else: 
        row['x_index'] = 'NaN'
        row['x_name'] = row['name']
        row['x_id'] = row['id']
        row['x_type'] = row['type']
        row['x_source'] = row['source']

    updated_rows.append(row)

updated_df = pd.DataFrame(updated_rows)
# drop columns 'x_id'
updated_df.drop(columns=['x_id_split'], inplace=True)
updated_df

,name,id,type,source,x_index,x_name,x_id,x_type,x_source
0,dementia,MESH:D003704,Disease,ncbi_mesh,37573,dementia (disease),1627,disease,MONDO
1,patients,9606,Species,ncbi_taxonomy,NaN,patients,9606,Species,ncbi_taxonomy
2,Alzheimer's disease,MESH:D000544,Disease,ncbi_mesh,28780,Alzheimer disease,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,MONDO_grouped
3,amyloid accumulation,MESH:C000718787,Disease,ncbi_mesh,NaN,amyloid accumulation,MESH:C000718787,disease,ncbi_mesh
4,cerebral vulnerability,MESH:D002547,Disease,ncbi_mesh,33667,cerebral palsy,6497,disease,MONDO
...,...,...,...,...,...,...,...,...,...
721,hepatitis C,MESH:D019698,Disease,ncbi_mesh,83799,chronic hepatitis C virus infection,5354,disease,MONDO
722,domestic violence/abuse,MESH:D019966,Disease,ncbi_mesh,36693,substance-related disorder,2494,disease,MONDO
723,knee pain,MESH:D046788,Disease,ncbi_mesh,97538,patellofemoral pain syndrome,6894,disease,MONDO
724,food insecurity,MESH:D005517,Disease,ncbi_mesh,NaN,food insecurity,MESH:D005517,disease,ncbi_mesh
725,respiratory diseases,MESH:D012140,Disease,ncbi_mesh,35553,respiratory system disease,5087,disease,MONDO

In [ ]:
updated_df.to_csv('data/updated_unmatchbio.csv', index=False)

In [44]:
import pandas as pd
updated_df = pd.read_csv('data/matchbio.csv', low_memory=False)

replace the corresponding information in SDoHKG

In [45]:
for index, row in SDoHKG.iterrows(): 
    updated_row = updated_df[(updated_df['name'] == row['x_name']) & (updated_df['id'] == row['x_id'])]
    if not updated_row.empty:
        updated_row = updated_row.iloc[0]
        SDoHKG.at[index, 'x_index'] = updated_row['x_index']
        SDoHKG.at[index, 'x_name'] = updated_row['x_name']
        SDoHKG.at[index, 'x_id'] = updated_row['x_id']
        SDoHKG.at[index, 'x_type'] = updated_row['x_type']
        SDoHKG.at[index, 'x_source'] = updated_row['x_source']
        
SDoHKG.to_csv('data/SDoHKG_matched.csv', index=False)
SDoHKG

,relation,x_index,x_name,x_id,x_type,x_source,y_index,y_name,y_id,y_type,y_source,pmid,probability
0,associates,37573.0,dementia (disease),1627,disease,MONDO,-1,diagnosis,NaN,SDoH factor,healthypeople,35301255.0,0.5
1,associates,37573.0,dementia (disease),1627,disease,MONDO,-1,disease-modifying treatments,NaN,SDoH factor,healthypeople,35301255.0,0.5
2,associates,37573.0,dementia (disease),1627,disease,MONDO,-1,elderly care,NaN,SDoH factor,healthypeople,35301255.0,0.5
3,associates,37573.0,dementia (disease),1627,disease,MONDO,-1,guidelines,NaN,SDoH factor,healthypeople,35301255.0,0.5
4,associates,37573.0,dementia (disease),1627,disease,MONDO,-1,protocols,NaN,SDoH factor,healthypeople,35301255.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4053,subordinate,-1.0,Poverty,NaN,SDoH subtype,healthypeople,-1,economic stability,NaN,SDoH type,healthypeople,NaN,1.0
4054,subordinate,-1.0,Access to Foods That Support Healthy Dietary P...,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4055,subordinate,-1.0,Crime and Violence,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4056,subordinate,-1.0,Environmental Conditions,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0
4057,subordinate,-1.0,Quality of Housing,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople,NaN,1.0

In [46]:
# find whether there are nan in the 'x_name' column
SDoHKG['y_source'].isnull().values.any()

False

### get primeKG subgraph

In [2]:
import pandas as pd
primekg = pd.read_csv('data\kg.csv', low_memory=False)
alzheimer = primekg.query('y_name=="Alzheimer disease"|x_name=="Alzheime disease"')
alzheimer

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
379115,contraindication,contraindication,20294,DB11160,drug,Phenyltoloxamine,DrugBank,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
379119,contraindication,contraindication,16490,DB01620,drug,Pheniramine,DrugBank,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
379123,contraindication,contraindication,15147,DB01173,drug,Orphenadrine,DrugBank,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
379127,contraindication,contraindication,17407,DB00175,drug,Pravastatin,DrugBank,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
379131,contraindication,contraindication,15832,DB00395,drug,Carisoprodol,DrugBank,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
...,...,...,...,...,...,...,...,...,...,...,...,...
5921563,disease_phenotype_positive,phenotype present,22671,11446,effect/phenotype,Abnormality of higher mental function,HPO,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
5921564,disease_phenotype_positive,phenotype present,90327,30219,effect/phenotype,Semantic dementia,HPO,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
6046106,disease_disease,parent-child,94982,10783,disease,"Alzheimer disease, susceptibility to, mitochon...",MONDO,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
6046901,disease_disease,parent-child,83960,11401,disease,Alzheimer disease without neurofibrillary tangles,MONDO,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped
6047037,disease_disease,parent-child,31527,11513,disease,"Alzheimer disease, familial early-onset, with ...",MONDO,28780,11913_7088_11743_12153_7089_11194_12321_15140_...,disease,Alzheimer disease,MONDO_grouped

In [3]:
def get_hops(df, start_node, max_hops=6):
    visited = set()  # Set to track visited nodes
    current_nodes = set([start_node])  # Start with the initial node

    for _ in range(max_hops):
        new_nodes = set()
        # Find all rows where the current set of nodes are mentioned in x_name or y_name
        query = df[(df['x_name'].isin(current_nodes)) | (df['y_name'].isin(current_nodes))]
        # Add all connected nodes to the new set
        new_nodes.update(query['x_name'].tolist())
        new_nodes.update(query['y_name'].tolist())
        # Update the visited nodes
        visited.update(current_nodes)
        # Update current_nodes with new nodes that haven't been visited
        current_nodes = new_nodes - visited

    return df[(df['x_name'].isin(visited)) | (df['y_name'].isin(visited))]

In [7]:
# Get 6 hops from 'Alzheimer disease'
alzheimer_hops = get_hops(primekg, 'Alzheimer disease', max_hops=4)

# Save the sub-graph to a new CSV file
alzheimer_hops.to_csv('data/alzheimer_sub_graph4.csv', index=False)

In [175]:
alzheimer_hops = pd.read_csv('data/alzheimer_sub_graph2.csv', low_memory=False)
alzheimer_hops

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
0,protein_protein,ppi,29,2147,gene/protein,F2,NCBI,844,6696,gene/protein,SPP1,NCBI
1,protein_protein,ppi,16,6633,gene/protein,SNRPD2,NCBI,216,23385,gene/protein,NCSTN,NCBI
2,protein_protein,ppi,33,2932,gene/protein,GSK3B,NCBI,4817,4853,gene/protein,NOTCH2,NCBI
3,protein_protein,ppi,33,2932,gene/protein,GSK3B,NCBI,8918,11033,gene/protein,ADAP1,NCBI
4,protein_protein,ppi,61,801,gene/protein,CALM1,NCBI,2621,3845,gene/protein,KRAS,NCBI
...,...,...,...,...,...,...,...,...,...,...,...,...
246617,anatomy_protein_absent,expression absent,63180,81,anatomy,metanephros,UBERON,2329,7124,gene/protein,TNF,NCBI
246618,anatomy_protein_absent,expression absent,63824,1377,anatomy,quadriceps femoris,UBERON,2329,7124,gene/protein,TNF,NCBI
246619,anatomy_protein_absent,expression absent,63826,1379,anatomy,vastus lateralis,UBERON,213,3630,gene/protein,INS,NCBI
246620,anatomy_protein_absent,expression absent,63952,1507,anatomy,biceps brachii,UBERON,213,3630,gene/protein,INS,NCBI
246621,anatomy_protein_absent,expression absent,64778,2349,anatomy,myocardium,UBERON,213,3630,gene/protein,INS,NCBI

In [176]:
# get the rows where the x_type or y_type is 'gene/protein','disease','drug'
alzheimer_sub = alzheimer_hops[alzheimer_hops['x_type'].isin(['gene/protein', 'disease', 'drug']) | alzheimer_hops['y_type'].isin(['gene/protein', 'disease', 'drug'])]
alzheimer_sub

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
0,protein_protein,ppi,29,2147,gene/protein,F2,NCBI,844,6696,gene/protein,SPP1,NCBI
1,protein_protein,ppi,16,6633,gene/protein,SNRPD2,NCBI,216,23385,gene/protein,NCSTN,NCBI
2,protein_protein,ppi,33,2932,gene/protein,GSK3B,NCBI,4817,4853,gene/protein,NOTCH2,NCBI
3,protein_protein,ppi,33,2932,gene/protein,GSK3B,NCBI,8918,11033,gene/protein,ADAP1,NCBI
4,protein_protein,ppi,61,801,gene/protein,CALM1,NCBI,2621,3845,gene/protein,KRAS,NCBI
...,...,...,...,...,...,...,...,...,...,...,...,...
246617,anatomy_protein_absent,expression absent,63180,81,anatomy,metanephros,UBERON,2329,7124,gene/protein,TNF,NCBI
246618,anatomy_protein_absent,expression absent,63824,1377,anatomy,quadriceps femoris,UBERON,2329,7124,gene/protein,TNF,NCBI
246619,anatomy_protein_absent,expression absent,63826,1379,anatomy,vastus lateralis,UBERON,213,3630,gene/protein,INS,NCBI
246620,anatomy_protein_absent,expression absent,63952,1507,anatomy,biceps brachii,UBERON,213,3630,gene/protein,INS,NCBI
246621,anatomy_protein_absent,expression absent,64778,2349,anatomy,myocardium,UBERON,213,3630,gene/protein,INS,NCBI

In [244]:
alzheimer_sub.to_csv('data/alzheimer_sub_graph.csv', index=False)

### generate dataset for link prediction

In [1]:
import pandas as pd
SDoHKG = pd.read_csv('data/SDoHKG_matched.csv', low_memory=False)
alzheimer_sub = pd.read_csv('data/alzheimer_sub_graph.csv', low_memory=False)

In [80]:
testdf1 = alzheimer_sub[['relation', 'x_index', 'x_name', 'x_id', 'x_type', 'x_source', 'y_index', 'y_name', 'y_id', 'y_type', 'y_source']]
testdf2 = SDoHKG[['relation', 'x_index', 'x_name', 'x_id', 'x_type', 'x_source', 'y_index', 'y_name', 'y_id', 'y_type', 'y_source']]
testdf = pd.concat([testdf1, testdf2], axis=0).reset_index(drop=True)
testdf.drop_duplicates(inplace=True)
testdf.reset_index(inplace=True)
testdf

,index,relation,x_index,x_name,x_id,x_type,x_source,y_index,y_name,y_id,y_type,y_source
0,0,protein_protein,29.0,F2,2147,gene/protein,NCBI,844,SPP1,6696,gene/protein,NCBI
1,1,protein_protein,16.0,SNRPD2,6633,gene/protein,NCBI,216,NCSTN,23385,gene/protein,NCBI
2,2,protein_protein,33.0,GSK3B,2932,gene/protein,NCBI,4817,NOTCH2,4853,gene/protein,NCBI
3,3,protein_protein,33.0,GSK3B,2932,gene/protein,NCBI,8918,ADAP1,11033,gene/protein,NCBI
4,4,protein_protein,61.0,CALM1,801,gene/protein,NCBI,2621,KRAS,3845,gene/protein,NCBI
...,...,...,...,...,...,...,...,...,...,...,...,...
249262,249305,subordinate,-1.0,Poverty,NaN,SDoH subtype,healthypeople,-1,economic stability,NaN,SDoH type,healthypeople
249263,249306,subordinate,-1.0,Access to Foods That Support Healthy Dietary P...,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople
249264,249307,subordinate,-1.0,Crime and Violence,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople
249265,249308,subordinate,-1.0,Environmental Conditions,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople
249266,249309,subordinate,-1.0,Quality of Housing,NaN,SDoH subtype,healthypeople,-1,neighborhood and built environment,NaN,SDoH type,healthypeople

In [81]:
testdf.to_csv('data/addsdoh.csv', index=False)

In [8]:
#testdf = pd.read_csv('data/addsdoh.csv', low_memory=False)
testdf = pd.read_csv('data/alzheimer_sub_graph.csv', low_memory=False)

In [9]:
testdf[testdf['x_name']=='Manganese']

,index,relation,x_index,x_name,x_id,x_type,x_source,y_index,y_name,y_id,y_type,y_source
8544,8547,drug_protein,15900.0,Manganese,DB06757,drug,DrugBank,4003,TF,7018,gene/protein,NCBI
186743,186764,exposure_protein,61759.0,Manganese,D008345,exposure,CTD,4003,TF,7018,gene/protein,NCBI
245265,245307,associates,15900.0,Manganese,DB06757,drug,DrugBank,-1,occupational,NaN,SDoH factor,healthypeople
247283,247325,is naturally found in,15900.0,Manganese,DB06757,drug,DrugBank,-1,environment,NaN,SDoH factor,healthypeople

In [10]:
t1 = testdf[['x_index', 'x_name', 'x_id', 'x_type', 'x_source']]
t2 = testdf[['y_index', 'y_name', 'y_id', 'y_type', 'y_source']]
t2.columns = ['x_index', 'x_name', 'x_id', 'x_type', 'x_source']
# concat pkg1 and pkg2
testid = pd.concat([t1, t2], axis=0)
testid = testid.drop_duplicates(subset=('x_name', 'x_type'))
#testid = testid.drop_duplicates(subset='x_name')
testid.reset_index(drop=True, inplace=True)

In [11]:
testid['x_index'] = testid.groupby('x_type').cumcount().astype(int)  
testid

,x_index,x_name,x_id,x_type,x_source
0,0,F2,2147,gene/protein,NCBI
1,1,SNRPD2,6633,gene/protein,NCBI
2,2,GSK3B,2932,gene/protein,NCBI
3,3,CALM1,801,gene/protein,NCBI
4,4,INS,3630,gene/protein,NCBI
...,...,...,...,...,...
19185,0,healthcare access and quality,NaN,SDoH type,healthypeople
19186,1,education access and quality,NaN,SDoH type,healthypeople
19187,2,social and community context,NaN,SDoH type,healthypeople
19188,3,economic stability,NaN,SDoH type,healthypeople
19189,4,neighborhood and built environment,NaN,SDoH type,healthypeople

In [6]:
# find 'x_name' = manganese in testid
testid[testid['x_name']=='Manganese']

      x_index     x_name     x_id    x_type  x_source
2179      972  Manganese  DB06757      drug  DrugBank
9388       29  Manganese  D008345  exposure       CTD

In [7]:
testid.to_csv('data/pkgid.csv', index=False)

In [8]:
genelist = ['APOE', 'TREM2', 'CD33', 'CLU', 'ABCA7', 'BIN1', 'CR1', 'SORL1', 'MS4A gene cluster', 'CD2AP', 'EPHA1', 'INPP5D', 'SHARPIN', 'TREML2', 'HLA-DR', 'ABI3', 'PLCG2', 'MEF2C', 'PICALM', 'C7', 'CASS4', 'SPI1', 'PTK2B', 'ADAMTS1', 'IGHG3', 'CLNK']
for i in genelist:
    print(testid[testid['x_name'] == i])

In [114]:
id_type = testid['x_type'].unique() 
dfs_by_type = {x_type: df_sub for x_type, df_sub in testid.groupby('x_type')}

for i in range(len(id_type)):
    subdf = dfs_by_type.get(id_type[i])
    subdf = subdf[['x_index']]
    subdf.columns = ['node_id']
    #path = 'data/rgcn/merge/nodes_'+str(i)+ '.csv'
    path = 'data/rgcn/pkg/nodes_'+str(i)+ '.csv'
    subdf.to_csv(path, index=False)

In [55]:
id_type

array(['gene/protein', 'drug', 'disease', 'effect/phenotype', 'exposure',
       'molecular_function', 'cellular_component', 'biological_process',
       'pathway', 'anatomy', 'Species', 'Variant', 'CellLine',
       'SDoH factor', 'SDoH subtype', 'SDoH type'], dtype=object)

In [115]:
testdf = testdf.merge(testid[['x_name', 'x_type', 'x_index']], how='left', left_on=['x_name', 'x_type'], right_on=['x_name', 'x_type'])
testdf = testdf.drop(columns=['x_index_x'])
testdf.rename(columns={'x_index_y': 'x_index'}, inplace=True)

# Merge to replace y_index
testdf = testdf.merge(testid[['x_name', 'x_type', 'x_index']], how='left', left_on=['y_name', 'y_type'], right_on=['x_name', 'x_type'])
testdf = testdf.drop(columns=['x_name_y', 'x_type_y', 'y_index'])
testdf.rename(columns={'x_index_y': 'y_index'}, inplace=True)
testdf.rename(columns={'x_index_x': 'x_index'}, inplace=True)
testdf.rename(columns={'x_name_x': 'x_name'}, inplace=True)
testdf.rename(columns={'x_type_x': 'x_type'}, inplace=True)

testdf

,relation,display_relation,x_id,x_type,x_name,x_source,y_id,y_type,y_name,y_source,x_index,y_index
0,protein_protein,ppi,2147,gene/protein,F2,NCBI,6696,gene/protein,SPP1,NCBI,0,1119
1,protein_protein,ppi,6633,gene/protein,SNRPD2,NCBI,23385,gene/protein,NCSTN,NCBI,1,5
2,protein_protein,ppi,2932,gene/protein,GSK3B,NCBI,4853,gene/protein,NOTCH2,NCBI,2,120
3,protein_protein,ppi,2932,gene/protein,GSK3B,NCBI,11033,gene/protein,ADAP1,NCBI,2,1436
4,protein_protein,ppi,801,gene/protein,CALM1,NCBI,3845,gene/protein,KRAS,NCBI,3,1437
...,...,...,...,...,...,...,...,...,...,...,...,...
245247,anatomy_protein_absent,expression absent,81,anatomy,metanephros,UBERON,7124,gene/protein,TNF,NCBI,108,40
245248,anatomy_protein_absent,expression absent,1377,anatomy,quadriceps femoris,UBERON,7124,gene/protein,TNF,NCBI,110,40
245249,anatomy_protein_absent,expression absent,1379,anatomy,vastus lateralis,UBERON,3630,gene/protein,INS,NCBI,111,4
245250,anatomy_protein_absent,expression absent,1507,anatomy,biceps brachii,UBERON,3630,gene/protein,INS,NCBI,113,4
245251,anatomy_protein_absent,expression absent,2349,anatomy,myocardium,UBERON,3630,gene/protein,INS,NCBI,116,4

In [116]:
testdf [(testdf['x_name']=='Manganese')|(testdf['y_name']=='Manganese')]

,relation,display_relation,x_id,x_type,x_name,x_source,y_id,y_type,y_name,y_source,x_index,y_index
8547,drug_protein,target,DB06757,drug,Manganese,DrugBank,7018,gene/protein,TF,NCBI,972,79
186764,exposure_protein,interacts with,D008345,exposure,Manganese,CTD,7018,gene/protein,TF,NCBI,29,79
204981,drug_protein,target,7018,gene/protein,TF,NCBI,DB06757,drug,Manganese,DrugBank,79,972
235582,exposure_protein,interacts with,7018,gene/protein,TF,NCBI,D008345,exposure,Manganese,CTD,79,29

In [117]:
t3 = testdf[['x_index','x_type','relation', 'y_index','y_type']] 
t3 = t3.dropna(subset=['x_index', 'y_index'])
t3['x_index'] = t3['x_index'].astype(int)
t3['y_index'] = t3['y_index'].astype(int)
t3

        x_index        x_type                relation  y_index        y_type
0             0  gene/protein         protein_protein     1119  gene/protein
1             1  gene/protein         protein_protein        5  gene/protein
2             2  gene/protein         protein_protein      120  gene/protein
3             2  gene/protein         protein_protein     1436  gene/protein
4             3  gene/protein         protein_protein     1437  gene/protein
...         ...           ...                     ...      ...           ...
245247      108       anatomy  anatomy_protein_absent       40  gene/protein
245248      110       anatomy  anatomy_protein_absent       40  gene/protein
245249      111       anatomy  anatomy_protein_absent        4  gene/protein
245250      113       anatomy  anatomy_protein_absent        4  gene/protein
245251      116       anatomy  anatomy_protein_absent        4  gene/protein

[245252 rows x 5 columns]

In [105]:
t3 [(t3 ['y_index'] == 972)|(t3 ['x_index'] == 972)]

,x_index,x_type,relation,y_index,y_type
3207,9,gene/protein,protein_protein,972,gene/protein
5140,972,gene/protein,protein_protein,79,gene/protein
8544,972,drug,drug_protein,79,gene/protein
163623,972,disease,disease_phenotype_positive,129,effect/phenotype
163624,972,disease,disease_phenotype_positive,131,effect/phenotype
174574,96,gene/protein,disease_protein,972,disease
185697,860,gene/protein,bioprocess_protein,972,biological_process
199620,972,gene/protein,protein_protein,9,gene/protein
201553,79,gene/protein,protein_protein,972,gene/protein
204957,79,gene/protein,drug_protein,972,drug
212422,129,effect/phenotype,disease_phenotype_positive,972,disease
212423,131,effect/phenotype,disease_phenotype_positive,972,disease
223373,972,disease,disease_protein,96,gene/protein
234494,972,biological_process,bioprocess_protein,860,gene/protein
245265,972,drug,associates,38,SDoH factor
247283,972,drug,is naturally found in,81,SDoH factor
248916,972,SDoH factor,subordinate,0,SDoH subtype

In [106]:
mapping_dict = {value: index for index, value in enumerate(id_type)}
mapping_dict

{'gene/protein': 0,
 'drug': 1,
 'disease': 2,
 'effect/phenotype': 3,
 'exposure': 4,
 'molecular_function': 5,
 'cellular_component': 6,
 'biological_process': 7,
 'pathway': 8,
 'anatomy': 9,
 'Species': 10,
 'Variant': 11,
 'CellLine': 12,
 'SDoH factor': 13,
 'SDoH subtype': 14,
 'SDoH type': 15}

In [118]:
grouped = t3.groupby(['x_type', 'y_type'])

# Create a dictionary to store the sub-DataFrames
subdfs = {group: subdf for group, subdf in grouped}
for key, subdf in subdfs.items():
    print(f"Sub-DataFrame for x_type = {key[0]} and y_type = {key[1]}:")
    print(subdf)
    print("\n")
    df_out = subdf[['x_index', 'y_index']]
    # rename the columns
    df_out.columns = ['src_id', 'dst_id']
    # save the sub-DataFrame to a CSV file
    #df_out.to_csv(f'data/rgcn/merge/edges_{mapping_dict[key[0]]}_{mapping_dict[key[1]]}.csv', index=False)
    df_out.to_csv(f'data/rgcn/pkg/edges_{mapping_dict[key[0]]}_{mapping_dict[key[1]]}.csv', index=False)

Sub-DataFrame for x_type = anatomy and y_type = gene/protein:
        x_index   x_type                 relation  y_index        y_type
236515        0  anatomy  anatomy_protein_present      104  gene/protein
236516        1  anatomy  anatomy_protein_present      104  gene/protein
236517        2  anatomy  anatomy_protein_present      104  gene/protein
236518        3  anatomy  anatomy_protein_present      104  gene/protein
236519        4  anatomy  anatomy_protein_present      104  gene/protein
...         ...      ...                      ...      ...           ...
245247      108  anatomy   anatomy_protein_absent       40  gene/protein
245248      110  anatomy   anatomy_protein_absent       40  gene/protein
245249      111  anatomy   anatomy_protein_absent        4  gene/protein
245250      113  anatomy   anatomy_protein_absent        4  gene/protein
245251      116  anatomy   anatomy_protein_absent        4  gene/protein

[8737 rows x 5 columns]


Sub-DataFrame for x_type = biological_process and y_type = gene/protein:
        x_index              x_type            relation  y_index        y_type
232452        0  biological_process  bioprocess_protein      205  gene/protein
232453        0  biological_process  bioprocess_protein       21  gene/protein
232454        0  biological_process  bioprocess_protein      640  gene/protein
232455        0  biological_process  bioprocess_protein      112  gene/protein
232456        0  biological_process  bioprocess_protein       36  gene/protein
...         ...                 ...                 ...      ...           ...
235489     1783  biological_process  bioprocess_protein     1421  gene/protein
235490     1784  biological_process  bioprocess_protein     1421  gene/protein
235491     1785  biological_process  bioprocess_protein     1421  gene/protein
235492     1786  biological_process  bioprocess_protein     1421  gene/protein
235493     1787  biological_process  bioprocess_protein     1426  gene/protein

[3042 rows x 5 columns]


Sub-DataFrame for x_type = cellular_component and y_type = gene/protein:
        x_index              x_type          relation  y_index        y_type
231437        0  cellular_component  cellcomp_protein      112  gene/protein
231438        1  cellular_component  cellcomp_protein       22  gene/protein
231439        1  cellular_component  cellcomp_protein      223  gene/protein
231440        1  cellular_component  cellcomp_protein       75  gene/protein
231441        1  cellular_component  cellcomp_protein       11  gene/protein
...         ...                 ...               ...      ...           ...
232447      266  cellular_component  cellcomp_protein       17  gene/protein
232448      267  cellular_component  cellcomp_protein      107  gene/protein
232449      268  cellular_component  cellcomp_protein       91  gene/protein
232450      269  cellular_component  cellcomp_protein       48  gene/protein
232451      270  cellular_component  cellcomp_protein      139  gene/protein

[1015 rows x 5 columns]


Sub-DataFrame for x_type = disease and y_type = disease:
        x_index   x_type         relation  y_index   y_type
175128     4242  disease  disease_disease     5138  disease
175129     4242  disease  disease_disease      739  disease
175130     4242  disease  disease_disease     5228  disease
175131     4243  disease  disease_disease     5229  disease
175132     4244  disease  disease_disease     4245  disease
...         ...      ...              ...      ...      ...
224238      377  disease  disease_disease     4245  disease
224239     5298  disease  disease_disease     4245  disease
224240     5299  disease  disease_disease     4242  disease
224241      335  disease  disease_disease     4242  disease
224242      293  disease  disease_disease     4242  disease

[592 rows x 5 columns]


Sub-DataFrame for x_type = disease and y_type = drug:
        x_index   x_type          relation  y_index y_type
205857     4254  disease  contraindication     1253   drug
205858     4255  disease  contraindication     1253   drug
205859     4254  disease  contraindication      756   drug
205860     4255  disease  contraindication      756   drug
205861     4254  disease  contraindication     1254   drug
...         ...      ...               ...      ...    ...
210207     3191  disease        indication       19   drug
210208     4620  disease        indication       19   drug
210209     4619  disease        indication       18   drug
210210     3191  disease        indication       18   drug
210211     4620  disease        indication       18   drug

[4355 rows x 5 columns]


Sub-DataFrame for x_type = disease and y_type = effect/phenotype:
        x_index   x_type                    relation  y_index  \
161933        0  disease  disease_phenotype_negative      117
161934        1  disease  disease_phenotype_negative      117
161935        2  disease  disease_phenotype_negative      117
161936        3  disease  disease_phenotype_negative      117
161937        4  disease  disease_phenotype_negative      117
...         ...      ...                         ...      ...
220027     4626  disease  disease_phenotype_positive        3
220028     4627  disease  disease_phenotype_positive        0
220029     4628  disease  disease_phenotype_positive        4
220030     4629  disease  disease_phenotype_positive        3
220031     4630  disease  disease_phenotype_positive        2

                  y_type
161933  effect/phenotype
161934  effect/phenotype
161935  effect/phenotype
161936  effect/phenotype
161937  effect/phenotype
...                  ...
220027  effect/phenotype
220028  effect/phenotype
220029  effect/phenotype
220030  effect/phenotype
220031  effect/phenotype

[9279 rows x 5 columns]


Sub-DataFrame for x_type = disease and y_type = exposure:
        x_index   x_type          relation  y_index    y_type
235810     4247  disease  exposure_disease        5  exposure
235811      896  disease  exposure_disease       60  exposure
235812     4310  disease  exposure_disease       60  exposure
235813     5300  disease  exposure_disease       60  exposure
235814       30  disease  exposure_disease       60  exposure
...         ...      ...               ...      ...       ...
236030     4834  disease  exposure_disease       51  exposure
236031     4843  disease  exposure_disease       51  exposure
236032     1186  disease  exposure_disease       51  exposure
236033     4247  disease  exposure_disease       53  exposure
236034     4247  disease  exposure_disease       56  exposure

[225 rows x 5 columns]


Sub-DataFrame for x_type = disease and y_type = gene/protein:
        x_index   x_type         relation  y_index        y_type
220032      543  disease  disease_protein      223  gene/protein
220033      543  disease  disease_protein       75  gene/protein
220034      543  disease  disease_protein       43  gene/protein
220035      543  disease  disease_protein      152  gene/protein
220036      543  disease  disease_protein       51  gene/protein
...         ...      ...              ...      ...           ...
223943     4315  disease  disease_protein       40  gene/protein
223944     4304  disease  disease_protein        4  gene/protein
223945     5226  disease  disease_protein       94  gene/protein
223946     4393  disease  disease_protein      532  gene/protein
223947     5227  disease  disease_protein       96  gene/protein

[3916 rows x 5 columns]


Sub-DataFrame for x_type = drug and y_type = disease:
       x_index x_type          relation  y_index   y_type
9423      1253   drug  contraindication     4254  disease
9424      1253   drug  contraindication     4255  disease
9425       756   drug  contraindication     4254  disease
9426       756   drug  contraindication     4255  disease
9427      1254   drug  contraindication     4254  disease
...        ...    ...               ...      ...      ...
13773       19   drug        indication     3191  disease
13774       19   drug        indication     4620  disease
13775       18   drug        indication     4619  disease
13776       18   drug        indication     3191  disease
13777       18   drug        indication     4620  disease

[4355 rows x 5 columns]


Sub-DataFrame for x_type = drug and y_type = drug:
        x_index x_type   relation  y_index y_type
13778       981   drug  drug_drug     1785   drug
13779        63   drug  drug_drug     1785   drug
13780        12   drug  drug_drug     1785   drug
13781        13   drug  drug_drug     1785   drug
13782        14   drug  drug_drug     1785   drug
...         ...    ...        ...      ...    ...
161387      149   drug  drug_drug     3536   drug
161388      149   drug  drug_drug     3537   drug
161389      149   drug  drug_drug     3541   drug
161390      149   drug  drug_drug     3542   drug
161391      149   drug  drug_drug      423   drug

[147614 rows x 5 columns]


Sub-DataFrame for x_type = drug and y_type = effect/phenotype:
        x_index x_type     relation  y_index            y_type
175425     1142   drug  drug_effect      111  effect/phenotype
175426     1142   drug  drug_effect        7  effect/phenotype
175427     3624   drug  drug_effect      142  effect/phenotype
175428     3624   drug  drug_effect        7  effect/phenotype
175429     3447   drug  drug_effect        7  effect/phenotype
...         ...    ...          ...      ...               ...
181854     2306   drug  drug_effect        7  effect/phenotype
181855     2306   drug  drug_effect        0  effect/phenotype
181856     2306   drug  drug_effect      132  effect/phenotype
181857     2306   drug  drug_effect      123  effect/phenotype
181858     2306   drug  drug_effect      133  effect/phenotype

[6434 rows x 5 columns]


Sub-DataFrame for x_type = drug and y_type = gene/protein:
      x_index x_type      relation  y_index        y_type
7106        0   drug  drug_protein       79  gene/protein
7107        1   drug  drug_protein       79  gene/protein
7108        2   drug  drug_protein       79  gene/protein
7109        3   drug  drug_protein       79  gene/protein
7110        4   drug  drug_protein       79  gene/protein
...       ...    ...           ...      ...           ...
9418      776   drug  drug_protein     4715  gene/protein
9419       66   drug  drug_protein       28  gene/protein
9420       67   drug  drug_protein       28  gene/protein
9421       66   drug  drug_protein      653  gene/protein
9422       67   drug  drug_protein      653  gene/protein

[2317 rows x 5 columns]


Sub-DataFrame for x_type = effect/phenotype and y_type = disease:
        x_index            x_type                    relation  y_index  \
171201        0  effect/phenotype  disease_phenotype_positive     4621
171202        1  effect/phenotype  disease_phenotype_positive     4622
171203        2  effect/phenotype  disease_phenotype_positive      896
171204        3  effect/phenotype  disease_phenotype_positive     4623
171205        0  effect/phenotype  disease_phenotype_positive     4624
...         ...               ...                         ...      ...
220016      116  effect/phenotype  disease_phenotype_positive     1822
220017        7  effect/phenotype  disease_phenotype_positive     4240
220018      117  effect/phenotype  disease_phenotype_positive     2245
220019      140  effect/phenotype  disease_phenotype_positive        8
220020      151  effect/phenotype  disease_phenotype_positive     4241

         y_type
171201  disease
171202  disease
171203  disease
171204  disease
171205  disease
...         ...
220016  disease
220017  disease
220018  disease
220019  disease
220020  disease

[9279 rows x 5 columns]


Sub-DataFrame for x_type = effect/phenotype and y_type = drug:
        x_index            x_type     relation  y_index y_type
224243      111  effect/phenotype  drug_effect     1142   drug
224244        7  effect/phenotype  drug_effect     1142   drug
224245      142  effect/phenotype  drug_effect     3624   drug
224246        7  effect/phenotype  drug_effect     3624   drug
224247        7  effect/phenotype  drug_effect     3447   drug
...         ...               ...          ...      ...    ...
230672        7  effect/phenotype  drug_effect     2306   drug
230673        0  effect/phenotype  drug_effect     2306   drug
230674      132  effect/phenotype  drug_effect     2306   drug
230675      123  effect/phenotype  drug_effect     2306   drug
230676      133  effect/phenotype  drug_effect     2306   drug

[6434 rows x 5 columns]


Sub-DataFrame for x_type = effect/phenotype and y_type = gene/protein:
        x_index            x_type           relation  y_index        y_type
210212        5  effect/phenotype  phenotype_protein      540  gene/protein
210213        5  effect/phenotype  phenotype_protein       94  gene/protein
210214        6  effect/phenotype  phenotype_protein       19  gene/protein
210215        7  effect/phenotype  phenotype_protein     1207  gene/protein
210216        7  effect/phenotype  phenotype_protein     1208  gene/protein
...         ...               ...                ...      ...           ...
210748      112  effect/phenotype  phenotype_protein     1414  gene/protein
210749      113  effect/phenotype  phenotype_protein      108  gene/protein
210750      114  effect/phenotype  phenotype_protein      697  gene/protein
210751      115  effect/phenotype  phenotype_protein     1409  gene/protein
210752      116  effect/phenotype  phenotype_protein     1415  gene/protein

[541 rows x 5 columns]


Sub-DataFrame for x_type = exposure and y_type = disease:
        x_index    x_type          relation  y_index   y_type
186992        5  exposure  exposure_disease     4247  disease
186993       60  exposure  exposure_disease      896  disease
186994       60  exposure  exposure_disease     4310  disease
186995       60  exposure  exposure_disease     5300  disease
186996       60  exposure  exposure_disease       30  disease
...         ...       ...               ...      ...      ...
187212       51  exposure  exposure_disease     4834  disease
187213       51  exposure  exposure_disease     4843  disease
187214       51  exposure  exposure_disease     1186  disease
187215       53  exposure  exposure_disease     4247  disease
187216       56  exposure  exposure_disease     4247  disease

[225 rows x 5 columns]


Sub-DataFrame for x_type = exposure and y_type = gene/protein:
        x_index    x_type          relation  y_index        y_type
186676        0  exposure  exposure_protein      152  gene/protein
186677        1  exposure  exposure_protein      291  gene/protein
186678        2  exposure  exposure_protein      152  gene/protein
186679        3  exposure  exposure_protein       40  gene/protein
186680        4  exposure  exposure_protein       96  gene/protein
...         ...       ...               ...      ...           ...
186987       56  exposure  exposure_protein       40  gene/protein
186988       57  exposure  exposure_protein       19  gene/protein
186989       58  exposure  exposure_protein       19  gene/protein
186990       58  exposure  exposure_protein       40  gene/protein
186991       59  exposure  exposure_protein       40  gene/protein

[316 rows x 5 columns]


Sub-DataFrame for x_type = gene/protein and y_type = anatomy:
        x_index        x_type                 relation  y_index   y_type
187697      104  gene/protein  anatomy_protein_present        0  anatomy
187698      104  gene/protein  anatomy_protein_present        1  anatomy
187699      104  gene/protein  anatomy_protein_present        2  anatomy
187700      104  gene/protein  anatomy_protein_present        3  anatomy
187701      104  gene/protein  anatomy_protein_present        4  anatomy
...         ...           ...                      ...      ...      ...
196429       40  gene/protein   anatomy_protein_absent      108  anatomy
196430       40  gene/protein   anatomy_protein_absent      110  anatomy
196431        4  gene/protein   anatomy_protein_absent      111  anatomy
196432        4  gene/protein   anatomy_protein_absent      113  anatomy
196433        4  gene/protein   anatomy_protein_absent      116  anatomy

[8737 rows x 5 columns]


Sub-DataFrame for x_type = gene/protein and y_type = biological_process:
        x_index        x_type            relation  y_index              y_type
183634      205  gene/protein  bioprocess_protein        0  biological_process
183635       21  gene/protein  bioprocess_protein        0  biological_process
183636      640  gene/protein  bioprocess_protein        0  biological_process
183637      112  gene/protein  bioprocess_protein        0  biological_process
183638       36  gene/protein  bioprocess_protein        0  biological_process
...         ...           ...                 ...      ...                 ...
186671     1421  gene/protein  bioprocess_protein     1783  biological_process
186672     1421  gene/protein  bioprocess_protein     1784  biological_process
186673     1421  gene/protein  bioprocess_protein     1785  biological_process
186674     1421  gene/protein  bioprocess_protein     1786  biological_process
186675     1426  gene/protein  bioprocess_protein     1787  biological_process

[3042 rows x 5 columns]


Sub-DataFrame for x_type = gene/protein and y_type = cellular_component:
        x_index        x_type          relation  y_index              y_type
182619      112  gene/protein  cellcomp_protein        0  cellular_component
182620       22  gene/protein  cellcomp_protein        1  cellular_component
182621      223  gene/protein  cellcomp_protein        1  cellular_component
182622       75  gene/protein  cellcomp_protein        1  cellular_component
182623       11  gene/protein  cellcomp_protein        1  cellular_component
...         ...           ...               ...      ...                 ...
183629       17  gene/protein  cellcomp_protein      266  cellular_component
183630      107  gene/protein  cellcomp_protein      267  cellular_component
183631       91  gene/protein  cellcomp_protein      268  cellular_component
183632       48  gene/protein  cellcomp_protein      269  cellular_component
183633      139  gene/protein  cellcomp_protein      270  cellular_component

[1015 rows x 5 columns]


Sub-DataFrame for x_type = gene/protein and y_type = disease:
        x_index        x_type         relation  y_index   y_type
171212      223  gene/protein  disease_protein      543  disease
171213       75  gene/protein  disease_protein      543  disease
171214       43  gene/protein  disease_protein      543  disease
171215      152  gene/protein  disease_protein      543  disease
171216       51  gene/protein  disease_protein      543  disease
...         ...           ...              ...      ...      ...
175123       40  gene/protein  disease_protein     4315  disease
175124        4  gene/protein  disease_protein     4304  disease
175125       94  gene/protein  disease_protein     5226  disease
175126      532  gene/protein  disease_protein     4393  disease
175127       96  gene/protein  disease_protein     5227  disease

[3916 rows x 5 columns]


Sub-DataFrame for x_type = gene/protein and y_type = drug:
        x_index        x_type      relation  y_index y_type
203540       79  gene/protein  drug_protein        0   drug
203541       79  gene/protein  drug_protein        1   drug
203542       79  gene/protein  drug_protein        2   drug
203543       79  gene/protein  drug_protein        3   drug
203544       79  gene/protein  drug_protein        4   drug
...         ...           ...           ...      ...    ...
205852     4715  gene/protein  drug_protein      776   drug
205853       28  gene/protein  drug_protein       66   drug
205854       28  gene/protein  drug_protein       67   drug
205855      653  gene/protein  drug_protein       66   drug
205856      653  gene/protein  drug_protein       67   drug

[2317 rows x 5 columns]

